### ISSUE TITLE
County_Level_Dataframe Problems (submitting for help and not grading)

### ISSUE THREAD

**Issue by jcmeinhardt** [SES-5215-F2020/jmeinhardt-quant#6]
Hi Carole! 

I'm submitting this issue per Sara's advice after trying to fix a problem with her in office hours today and us both coming up empty for a solution. 
I've posted the link below to the Rmd, and there are some comments in there as well to help explain the problem. But I'll try to explain it here very shortly.

1. I went back to this data frame I submitted for Assignment 1 and changed some variables. 
3. Now I'm having a problem when mutating my hs_grads variable (which I did not have trouble mutating during the first iteration). In first iteration, I mutated it to determine if counties met the statewide graduation threshold percentage of 83% or greater. The vast majority of them did meet that threshold, as expected. 
4. Now, when I mutate with that same threshold, it's reading all tracts and counties as not meeting that threshold, unlike previously, and has a total count of hs graduates as much lower than before. 

Any help is appreciated—Sara and I were at a loss for what could be going on! 

https://github.com/SES-5215-F2020/jmeinhardt-quant/blob/master/County_Level_Dataframe.Rmd

*One other note: at the beginning of the semester, I mistakenly cloned my repo for quant a few times, so I have some file management problems going. I'm not sure if this could be part of the problem or not. If so (and probably regardless), I'll need to sign up for office hours to walk through how to clean up the mess I made there. 

Thank you!

Julia

**Comment by c-voulgaris** [comment]
I'm leaving this comment here to let you know I've seen this, and I'll take a closer look as soon as I can.

**Comment by c-voulgaris** [comment]
I can't speak to what was going on before, but I think this code is working the way it should. 

The variable B06009_003 is the number of people who have graduated from high school, but don't have any further education (e.g. they aren't included in the number of people with some college, or with a college degree). To get the total number of people who have graduated from high school, regardless of whether they have gone on to get further education, I suggest taking the value of B06009_02 and subtracting it from the total population.

**Comment by c-voulgaris** [comment]
Replace line 78 with:               

```
lt_hs_grads =    "B06009_002",
```

And replace line 85 with:

```
  mutate(majority_grads = (total_popE - lt_hs_gradsE)/total_popE > 0.83,
```

And you'll find that 88% of your tracts meet that 83% threshold.
